// 문항 풀 — 최신 신조어 20 + 레트로 유행어 20 = 총 40문항.
// 스키마: { id, direction, question, choices[4], answerIndex(0-based), eraYear, explain }
// 엔진은 pool-agnostic 이므로 앱이 이 배열을 generatePaper 에 주입한다.
//
// ⚠️ 출시 전 사용자 최신성 검수 필수(재미 진단이므로 유행 시점·의미가 생명):
//   - 신조어(NEW): 2025~26 최신 표현으로 상시 교체·보강. eraYear 는 대략적 유행 시작 연도.
//   - 레트로(RETRO): 1995~2010 표현. 의미·유래를 사용자가 세대 감수성 기준으로 확인.
//   - "재미용 진단이며 언어 능력·세대를 규정하지 않는다"는 포지셔닝 유지.

import type { Item } from "@/lib/shinjo-engine";

// ── 최신 신조어 (NEW) 20 ───────────────────────────────────────────────
const NEW: Item[] = [
  {
    id: "N01",
    direction: "new",
    question: '"갓생 산다"에서 \'갓생\'의 뜻은?',
    choices: ["부지런하고 알차게 사는 삶", "신을 믿는 삶", "게임만 하는 삶", "혼자 사는 삶"],
    answerIndex: 0,
    eraYear: 2022,
    explain: "god(갓)+생(生). 규칙적이고 생산적으로 사는 모범적인 삶을 뜻한다.",
  },
  {
    id: "N02",
    direction: "new",
    question: '"난 얼죽아야"에서 \'얼죽아\'는?',
    choices: ["얼굴 죽여주게 아름다움", "얼어 죽어도 아이스 아메리카노", "얼른 죽자 아무나", "얼굴 죽은 아침"],
    answerIndex: 1,
    eraYear: 2019,
    explain: "‘얼어 죽어도 아이스 아메리카노’의 준말. 한겨울에도 아아를 고집하는 사람.",
  },
  {
    id: "N03",
    direction: "new",
    question: "‘꾸안꾸’ 스타일이란?",
    choices: ["꾸미다 안 꾸미다 반복", "꾸민 듯 안 꾸민 듯", "꾸준히 안 꾸미는", "꾸중 안 듣게 꾸미는"],
    answerIndex: 1,
    eraYear: 2019,
    explain: "‘꾸민 듯 안 꾸민 듯’. 힘을 뺀 듯하지만 은근히 신경 쓴 스타일.",
  },
  {
    id: "N04",
    direction: "new",
    question: "‘알잘딱깔센’을 풀어 쓰면?",
    choices: ["알아서 잘 딱 깔끔하고 센스있게", "알고 보니 딱히 깔끔한 센스", "알바 잘하는 딱한 센스", "알아두면 잘 딱 깔리는 센스"],
    answerIndex: 0,
    eraYear: 2021,
    explain: "‘알아서 잘 딱 깔끔하고 센스있게’의 앞글자. 눈치껏 알아서 처리하란 뜻.",
  },
  {
    id: "N05",
    direction: "new",
    question: '누가 "어쩔티비"라고 하면?',
    choices: ["티비를 켜라는 부탁", "어쩌라고를 놀리듯 받아치는 말", "어제 본 티비 얘기", "어쩔 수 없다는 체념"],
    answerIndex: 1,
    eraYear: 2021,
    explain: "‘어쩌라고’를 장난스럽게 받아치는 말. ‘저쩔티비’ 등으로 응수하며 논다.",
  },
  {
    id: "N06",
    direction: "new",
    question: "‘킹받다’의 뜻은?",
    choices: ["매우 기쁘다", "왕이 되다", "몹시 화가 나다", "복권에 당첨되다"],
    answerIndex: 2,
    eraYear: 2021,
    explain: "king(킹)+열받다. ‘열받다’를 과장해 몹시 화나거나 얄미운 상황에 쓴다.",
  },
  {
    id: "N07",
    direction: "new",
    question: "‘스불재’란?",
    choices: ["스스로 불러온 재앙", "스마트폰 불량 재고", "스트레스 불면 재발", "스승이 불러준 재능"],
    answerIndex: 0,
    eraYear: 2022,
    explain: "‘스스로 불러온 재앙’의 준말. 자기가 자초한 곤란한 상황을 뜻한다.",
  },
  {
    id: "N08",
    direction: "new",
    question: '헬스장 인증글 "오운완"의 뜻은?',
    choices: ["오늘 운동 완료", "오래 운동 완패", "오전 운동 완성", "오늘 운세 완벽"],
    answerIndex: 0,
    eraYear: 2022,
    explain: "‘오늘 운동 완료’. SNS에 운동 인증할 때 붙이는 대표 해시태그.",
  },
  {
    id: "N09",
    direction: "new",
    question: '"점메추 좀"이라고 하면 뭘 부탁하는 걸까?',
    choices: ["점수 매기기 추천", "점심 메뉴 추천", "점점 메마른 추억", "점검 메일 추가"],
    answerIndex: 1,
    eraYear: 2021,
    explain: "‘점심 메뉴 추천’의 준말. ‘저메추(저녁 메뉴 추천)’와 짝을 이룬다.",
  },
  {
    id: "N10",
    direction: "new",
    question: "맛있는 음식 사진에 다는 ‘군싹’은?",
    choices: ["군더더기 싹 뺀", "군침이 싹 도네", "군고구마 싹쓸이", "군소리 싹 없는"],
    answerIndex: 1,
    eraYear: 2022,
    explain: "‘군침이 싹 도네’의 준말. 한 예능 장면에서 유행해 밈이 되었다.",
  },
  {
    id: "N11",
    direction: "new",
    question: "‘삼귀다’는 어떤 사이?",
    choices: ["세 명이 사귀다", "사귀기 직전(썸) 단계", "삼 년째 사귀다", "삼시세끼 함께"],
    answerIndex: 1,
    eraYear: 2021,
    explain: "‘사귀다’의 ‘사(4)’를 ‘삼(3)’으로 낮춘 말장난. 아직 사귀기 전 단계.",
  },
  {
    id: "N12",
    direction: "new",
    question: '"그만 좀 해, 뇌절이야"에서 \'뇌절\'은?',
    choices: ["머리가 좋다", "같은 말·행동을 반복해 질리게 함", "뇌가 멈춘 상태", "절묘한 아이디어"],
    answerIndex: 1,
    eraYear: 2021,
    explain: "같은 개그·말을 자꾸 반복해 재미가 식는 것. ‘1절만 해’에서 확장됐다.",
  },
  {
    id: "N13",
    direction: "new",
    question: "‘폼 미쳤다’는 언제 쓸까?",
    choices: ["옷이 구겨졌을 때", "실력이나 상태가 최고조일 때", "몸살이 났을 때", "지루할 때"],
    answerIndex: 1,
    eraYear: 2023,
    explain: "form(폼)+미쳤다. 컨디션·실력·비주얼이 절정일 때 감탄으로 쓴다.",
  },
  {
    id: "N14",
    direction: "new",
    question: "‘갑통알’이 뜻하는 상황은?",
    choices: ["갑자기 통화 알림", "갑자기 통장 보니 알바해야 함", "갑질 통보 알림", "갑작스런 통증 알림"],
    answerIndex: 1,
    eraYear: 2021,
    explain: "‘갑자기 통장을 보니 알바(일)해야겠다’. 잔고를 보고 정신 차릴 때.",
  },
  {
    id: "N15",
    direction: "new",
    question: "대화가 ‘티키타카’ 된다는 건?",
    choices: ["말이 자꾸 끊긴다", "호흡·대화가 척척 잘 맞는다", "말싸움이 난다", "말이 너무 빠르다"],
    answerIndex: 1,
    eraYear: 2020,
    explain: "축구의 짧은 패스 전술에서 온 말. 주고받는 호흡이 찰떡같이 맞을 때.",
  },
  {
    id: "N16",
    direction: "new",
    question: "‘완내스’의 뜻은?",
    choices: ["완전 내 스타일", "완벽한 내일 스케줄", "완전 내성적", "완성된 내부 시스템"],
    answerIndex: 0,
    eraYear: 2023,
    explain: "‘완전 내 스타일’의 준말. 취향에 딱 맞을 때 감탄사처럼 쓴다.",
  },
  {
    id: "N17",
    direction: "new",
    question: '"그 약속 캘박하자"에서 \'캘박\'은?',
    choices: ["캘린더에 박제(일정 확정)", "캘린더 박살", "캐리어 박스", "캘리그라피 박람회"],
    answerIndex: 0,
    eraYear: 2023,
    explain: "‘캘린더에 박제’. 일정을 달력에 못 박아 확정한다는 뜻.",
  },
  {
    id: "N18",
    direction: "new",
    question: "‘억텐’은 어떤 상태?",
    choices: ["억울한 텐션", "억지 텐션(억지로 끌어올린 기운)", "억대 텐트", "억센 텐션"],
    answerIndex: 1,
    eraYear: 2021,
    explain: "‘억지 텐션’의 준말. 흥이 안 나는데 억지로 신난 척할 때. 반대는 ‘찐텐’.",
  },
  {
    id: "N19",
    direction: "new",
    question: '"그건 사바사지"에서 \'사바사\'는?',
    choices: ["사람 by 사람(사람마다 다름)", "사이좋은 바다 사진", "사고 바로 사과", "사장 바뀐 사무실"],
    answerIndex: 0,
    eraYear: 2020,
    explain: "‘사람 by 사람’. 경우마다 다르다는 뜻. ‘케바케(case by case)’의 사람 버전.",
  },
  {
    id: "N20",
    direction: "new",
    question: "첫인사로 보낸 ‘만반잘부’는?",
    choices: ["만나서 반가워 잘 부탁해", "만 원 반값 잘 부탁", "만능 반찬 잘 부탁", "만날 반복 잘 부탁"],
    answerIndex: 0,
    eraYear: 2019,
    explain: "‘만나서 반가워 잘 부탁해’의 앞글자. 새 친구·팔로워에게 건네는 인사.",
  },
];

// ── 레트로 유행어 (RETRO) 20 ──────────────────────────────────────────
const RETRO: Item[] = [
  {
    id: "R01",
    direction: "retro",
    question: '2000년대 초 "당근이지~"의 뜻은?',
    choices: ["당황스럽다", "당연하지", "당장 가자", "당근을 좋아해"],
    answerIndex: 1,
    eraYear: 2001,
    explain: "‘당연하지’를 귀엽게 비튼 말. 한 광고에서 유행해 전국구가 됐다.",
  },
  {
    id: "R02",
    direction: "retro",
    question: "그 시절 ‘얼짱’이 가리키는 사람은?",
    choices: ["얼굴이 매우 예쁘거나 잘생긴 사람", "얼음처럼 차가운 사람", "얼렁뚱땅 잘하는 사람", "얼굴이 큰 사람"],
    answerIndex: 0,
    eraYear: 2001,
    explain: "‘얼굴+짱’. 2000년대 초 인터넷 ‘얼짱 시대’를 연 대표 신조어.",
  },
  {
    id: "R03",
    direction: "retro",
    question: "‘안습’은 어떤 상황에 썼을까?",
    choices: ["안전제일 습관", "안구에 습기, 눈물 날 만큼 안타까움", "안쪽이 축축함", "안심되고 습한 날씨"],
    answerIndex: 1,
    eraYear: 2004,
    explain: "‘안구에 습기’. 딱하거나 안타까운 장면을 볼 때 쓰던 초창기 인터넷 유행어.",
  },
  {
    id: "R04",
    direction: "retro",
    question: "채팅창 인사 ‘방가방가’의 뜻은?",
    choices: ["방을 청소하자", "반가워(반가움을 귀엽게)", "방금 도착했어", "방해하지 마"],
    answerIndex: 1,
    eraYear: 1999,
    explain: "‘반가워’를 귀엽게 반복한 90년대 말 PC통신·채팅 인사말.",
  },
  {
    id: "R05",
    direction: "retro",
    question: "옛날 메신저에서 ‘하이루’는?",
    choices: ["높은 곳", "안녕(인사말)", "하위 목록", "하루 종일"],
    answerIndex: 1,
    eraYear: 2000,
    explain: "영어 ‘hi’에 ‘루’를 붙인 2000년 전후 채팅 인사. ‘하이룽’으로도 썼다.",
  },
  {
    id: "R06",
    direction: "retro",
    question: '누가 채팅에서 "즐~"이라고 하면?',
    choices: ["즐겁게 놀자는 진심", "비꼬며 상대를 무시·거절하는 말", "즉시 만나자는 뜻", "졸리다는 표현"],
    answerIndex: 1,
    eraYear: 2003,
    explain: "겉은 ‘즐거운 하루 되세요’지만 속뜻은 무시·비꼼. 2000년대 대표 시전어.",
  },
  {
    id: "R07",
    direction: "retro",
    question: "‘지못미’를 풀어 쓰면?",
    choices: ["지금 못 만나 미안", "지켜주지 못해 미안", "지겨워도 못 미뤄", "지각해서 못 미안"],
    answerIndex: 1,
    eraYear: 2008,
    explain: "‘지켜주지 못해 미안’. 굴욕 사진 등에 안쓰러움을 담아 붙이던 말.",
  },
  {
    id: "R08",
    direction: "retro",
    question: "‘솔까말’의 뜻은?",
    choices: ["솔직히 까놓고 말해서", "솔로는 까다로운 말", "솔솔 까먹는 말", "솔직한 까칠한 말투"],
    answerIndex: 0,
    eraYear: 2008,
    explain: "‘솔직히 까놓고 말해서’의 앞글자. 본심을 꺼낼 때 서두에 붙였다.",
  },
  {
    id: "R09",
    direction: "retro",
    question: "게시판 댓글 ‘흠좀무’의 뜻은?",
    choices: ["흠집이 좀 무섭다", "흠, 이게 사실이면 좀 무섭다", "흠뻑 젖어 좀 무겁다", "흠모하는 좀 무던한"],
    answerIndex: 1,
    eraYear: 2008,
    explain: "‘흠… 이게 사실이라면 좀 무섭다’의 준말. 놀라운 정보에 반신반의할 때.",
  },
  {
    id: "R10",
    direction: "retro",
    question: "‘귀차니즘’이 뜻하는 상태는?",
    choices: ["귀를 막는 태도", "만사가 귀찮은 상태·태도", "귀한 대접을 받는 삶", "귀신을 믿는 사상"],
    answerIndex: 1,
    eraYear: 2003,
    explain: "‘귀찮다’에 ‘-ism(주의)’를 붙인 말장난. 게으름을 하나의 신조처럼 표현.",
  },
  {
    id: "R11",
    direction: "retro",
    question: "‘완소남’의 ‘완소’는?",
    choices: ["완전 소심한", "완전 소중한", "완벽하고 소탈한", "완성된 소년"],
    answerIndex: 1,
    eraYear: 2006,
    explain: "‘완전 소중한’의 준말. ‘완소템(완전 소중한 아이템)’처럼도 썼다.",
  },
  {
    id: "R12",
    direction: "retro",
    question: "‘셀카’의 원래 뜻은?",
    choices: ["셀프 카메라(스스로 찍는 사진)", "셀렘 가득한 카드", "셀러브리티 카페", "셀 수 없는 카운트"],
    answerIndex: 0,
    eraYear: 2003,
    explain: "‘셀프 카메라’의 준말. 디카·폴더폰 시절 팔 뻗어 찍던 자가 촬영.",
  },
  {
    id: "R13",
    direction: "retro",
    question: "‘넘사벽’을 풀어 쓰면?",
    choices: ["넘어진 사람 벽", "넘을 수 없는 사차원의 벽", "너무 사소한 벽", "넘치는 사랑의 벽"],
    answerIndex: 1,
    eraYear: 2009,
    explain: "‘넘을 수 없는 사차원의 벽’. 도저히 따라잡을 수 없는 압도적 격차.",
  },
  {
    id: "R14",
    direction: "retro",
    question: "2000년대 후반 ‘병맛’의 뜻은?",
    choices: ["병에 든 음료 맛", "어이없고 형편없어 오히려 웃긴 것", "몸이 아픈 상태", "병원 밥맛"],
    answerIndex: 1,
    eraYear: 2008,
    explain: "맥락 없고 허술하지만 그래서 웃긴 B급 감성. 웹툰·짤 문화와 함께 퍼졌다.",
  },
  {
    id: "R15",
    direction: "retro",
    question: "‘짤방’은 무엇이었을까?",
    choices: ["짧은 방송", "글 삭제(짤림) 방지용 이미지", "짤랑거리는 방울", "짜증 방지 장치"],
    answerIndex: 1,
    eraYear: 2003,
    explain: "게시글이 ‘짤리는’ 걸 막으려 넣던 이미지. 오늘날 ‘짤’의 어원이 됐다.",
  },
  {
    id: "R16",
    direction: "retro",
    question: "게임에서 온 ‘득템’의 뜻은?",
    choices: ["원하는 아이템을 얻음", "점수를 잃음", "템포를 놓침", "특별히 템스강에 감"],
    answerIndex: 0,
    eraYear: 2004,
    explain: "‘아이템을 득(得)하다’. 게임에서 나와 좋은 물건을 싸게 산 상황에도 썼다.",
  },
  {
    id: "R17",
    direction: "retro",
    question: "‘리즈시절’이 가리키는 때는?",
    choices: ["리듬을 타던 시절", "인생 최고 전성기였던 때", "리허설 하던 시절", "리스트를 만들던 때"],
    answerIndex: 1,
    eraYear: 2010,
    explain: "축구선수의 리즈 유나이티드 전성기에서 유래. 가장 빛나던 시기를 뜻한다.",
  },
  {
    id: "R18",
    direction: "retro",
    question: "‘므흣’이 표현하는 감정은?",
    choices: ["몹시 화남", "흐뭇하면서 야릇한 미소", "무섭고 흉함", "무료하고 심심함"],
    answerIndex: 1,
    eraYear: 2004,
    explain: "‘흐뭇’을 변형한 의태어. 야릇하거나 만족스러운 미소를 지을 때 썼다.",
  },
  {
    id: "R19",
    direction: "retro",
    question: '외계어 "뷁"은 어떤 느낌으로 썼을까?',
    choices: ["기쁘고 상쾌할 때", "황당하거나 어이없을 때", "졸리고 지칠 때", "배고플 때"],
    answerIndex: 1,
    eraYear: 2004,
    explain: "발음할 수 없는 글자로 황당함·어이없음을 내지르던 2000년대 외계어.",
  },
  {
    id: "R20",
    direction: "retro",
    question: "‘볼매’는 어떤 사람?",
    choices: ["볼이 통통한 사람", "볼수록 매력 있는 사람", "볼일 많은 사람", "볼링 매니아"],
    answerIndex: 1,
    eraYear: 2008,
    explain: "‘볼수록 매력 있다’의 준말. 첫인상보다 알수록 좋아지는 사람을 뜻한다.",
  },
];

/** 전체 문항 풀 (최신 20 + 레트로 20) */
export const ITEMS: Item[] = [...NEW, ...RETRO];
